version: '3.8'

services:
  app:
    container_name: app
    image: 'php8.2-fpm'
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks: 
      - laravel

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: 'cicd'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - mysqldb:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
  
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - mysqldb:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysqldb:
    driver: local