name: Bismillah Gacor

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: gesangwidigdo/tamiyochi-laravel:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Git Checkout
        uses: actions/checkout@v4.1.6
      -
        name: Copy docker-compose.yaml to SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "./docker-compose.yaml, ./nginx/default.conf, ./mysql/my.cnf, ./php/local.ini"
          target: "."
          overwrite: true
      -
        name: Deploy to Cloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd ~
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tamiyochi-laravel:latest
            docker compose up -d
            docker exec -i app php artisan migrate --force
            docker exec -i app php artisan db:seed --force